### ISSUE TITLE
Possible issue with whitelist and testing

### ISSUE THREAD

**Issue by federicodonner** [federicodonner/pendientes_recargana_IV#10]
Sent a test topup to 95915475. It got the link
http://xrink.me/0uNyV
It links to a webpage saying the game is over. We couldn't test it with that URL.
![270f270c-7314-4a1a-b0e0-ef4a6afd1e03](https://user-images.githubusercontent.com/18017111/109330357-58e87e00-783a-11eb-8fe0-b578f0585104.jpg)

**Comment by joaobastos89** [comment]
Done

**Comment by joaobastos89** [comment]
Done, había un error en el link de las MT, arreglado ayer.
