### ISSUE TITLE
Recibo el mensaje SMS para jugar (recarga < $200) y me dice que la promo terminó

### ISSUE THREAD

**Issue by litalring** [federicodonner/pendientes_recargana_IV#11]
![no deja jugar](https://user-images.githubusercontent.com/70407933/109331891-2b9ccf80-783c-11eb-955b-71d835cb700d.jpg)
![mensaje de recargana](https://user-images.githubusercontent.com/70407933/109331897-2d669300-783c-11eb-944b-d73eae7c6a7b.jpg)

**Comment by litalring** [comment]
Es el cel de pruebas: 095 91 5475

**Comment by litalring** [comment]
Me dio el mismo mensaje entrando a otro link que me mandaron

**Comment by joaobastos89** [comment]
Done
