### ISSUE TITLE
Dice Mes atual en lugar de Mes actual

### ISSUE THREAD

**Issue by litalring** [federicodonner/pendientes_recargana_IV#13]
<img width="378" alt="Mes atual" src="https://user-images.githubusercontent.com/70407933/109347930-a1139a80-7852-11eb-9b78-faf2f097d012.png">

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
![Screenshot_2021-03-01-08-14-26-826_com android chrome](https://user-images.githubusercontent.com/60514253/109489865-3b97f780-7a66-11eb-839d-8d4fe7074a8f.jpg)
Pronto
