### ISSUE TITLE
Detalle de raspaditas pendientes - nombre

### ISSUE THREAD

**Issue by mgonzalezbilli** [federicodonner/pendientes_recargana_IV#14]
Las raspaditas deberían llamarse "raspaditas", no "raspa premiada"
![dcd7891b-a8fc-4172-be26-19aeef997961](https://user-images.githubusercontent.com/60514253/109349388-a376f400-7854-11eb-9b47-18fcfc7bff83.jpg)

**Comment by mgonzalezbilli** [comment]
![image](https://user-images.githubusercontent.com/60514253/109352540-c3f57d00-7859-11eb-9f42-d66a20708c56.png)

**Comment by mgonzalezbilli** [comment]
Nombrar la dorara como raspadita especial y la celeste como raspadita

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
Resuelto 
![Uploading Screenshot_2021-03-01-10-03-46-413_com.mi.globalbrowser.jpg…]()
