### ISSUE TITLE
Prueba con 095 915475- 2 recargas de $100 , no acumularon 1 Cupón 

### ISSUE THREAD

**Issue by litalring** [federicodonner/pendientes_recargana_IV#15]
<img width="378" alt="No acumula" src="https://user-images.githubusercontent.com/70407933/109350411-395f4e80-7856-11eb-85ad-2ee2b5421dd4.png">

**Comment by joaobastos89** [comment]
Done, habia un error en el link de las MT, corrigido ayer

**Comment by mgonzalezbilli** [comment]
Probado
