### ISSUE TITLE
Prueba recarga $200, en el link no me deja raspar (dice que tengo raspaditas disponibles)

### ISSUE THREAD

**Issue by litalring** [federicodonner/pendientes_recargana_IV#16]
![mensaje $200](https://user-images.githubusercontent.com/70407933/109351168-90195800-7857-11eb-9efa-3dc60170db54.jpg)
![raspaditas disponibles](https://user-images.githubusercontent.com/70407933/109351174-91e31b80-7857-11eb-9106-9992bd11ee48.jpg)

**Comment by mgonzalezbilli** [comment]
Solucionado al limpiar cache
