### ISSUE TITLE
Lower buttons don't indicate current section

### ISSUE THREAD

**Issue by federicodonner** [federicodonner/pendientes_recargana_IV#17]
Premios, Inicio and Raspaditas.
The current section should light up or be highlighted somehow.

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
Probado
![IMG_20210301_082743](https://user-images.githubusercontent.com/60514253/109491194-08566800-7a68-11eb-8b14-ff676cbe4ca2.jpg)
