### ISSUE TITLE
Unclear Raspaditas section

### ISSUE THREAD

**Issue by federicodonner** [federicodonner/pendientes_recargana_IV#19]
Raspaditas section has a button that says
`Raspaditas Disponibles`
But can't be clicked, it's not clear what the user should do in that screen.

**Comment by federicodonner** [comment]
Now I understand, it's not a button, it's a title. 
`Raspaditas Disponibles` should not look like a button.
When there are no Raspaditas available it should have a message like
`No tienes Raspaditas disponibles, recarga $200 o más para jugar.`

**Comment by mgonzalezbilli** [comment]
Sigue sin resolverse

**Comment by mgonzalezbilli** [comment]
Resuelto
![Screenshot_2021-03-01-09-55-46-276_com mi globalbrowser](https://user-images.githubusercontent.com/60514253/109499943-55403b80-7a74-11eb-808c-1ae5b726f785.jpg)
