### ISSUE TITLE
Premios de Febrero

### ISSUE THREAD

**Issue by mgonzalezbilli** [federicodonner/pendientes_recargana_IV#2]
Está figurando Febrero como mes inicial de Recarganá con las cámaras como premio
![image](https://user-images.githubusercontent.com/60514253/109175560-abf00180-7764-11eb-9a3d-bfb10c4ad60e.png)

**Comment by jonml9118** [comment]
Hello,

The Month of February is currently configured only as a dummy so UATs are possible during this month and the actual draws start only when the service goes live, without any testing msisdns participating in it. Before the goLive date, this will be removed and the month of March will appear as the first month.
