### ISSUE TITLE
First top-up not registered

### ISSUE THREAD

**Issue by federicodonner** [federicodonner/pendientes_recargana_IV#20]
Tried a $200 top-up for 94912671, got the SMS with the link but I don't see any Raspaditas or accumulated topups in the interface.

**Comment by federicodonner** [comment]
Added another top-up for this line and nothing changed in the app. There is probably an issue with whitelisting of this line.

**Comment by joaobastos89** [comment]
There was a problem with the link coming from the MT, corrected yesterday. Please clear the cache and test again

**Comment by mgonzalezbilli** [comment]
Solved
