### ISSUE TITLE
When Recarga Acumulada = 0, nothing shows.

### ISSUE THREAD

**Issue by federicodonner** [federicodonner/pendientes_recargana_IV#21]

**Comment by federicodonner** [comment]
On Inicio in the app y see the blue rectangle
`RECARGA ACUMULADA = $`

**Comment by joaobastos89** [comment]
Not sure if I understood the issue... You suggest to have "0$", instead of " $" in recarga acumulada counter?

**Comment by federicodonner** [comment]
Yes, having no number looks like que UI is broken, it should be
`RECARGA ACUMULADA = $0`

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
Chequeado
