### ISSUE TITLE
Los premios de megas aparecen con la esfera de gigas

### ISSUE THREAD

**Issue by mgonzalezbilli** [federicodonner/pendientes_recargana_IV#22]
Para los premios de 100 y 300mb en las raspaditas menores a $200, la esfera deberia decir megas
![IMG-20210227-WA0019](https://user-images.githubusercontent.com/60514253/109395293-5c4b3a80-790a-11eb-88f8-8fc30ee8d395.jpg)

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
Resuelto
![Uploading Screenshot_2021-03-01-10-04-46-973_com.mi.globalbrowser.jpg…]()
