### ISSUE TITLE
Al dar siguiente sin pin, el mensaje está en portugués

### ISSUE THREAD

**Issue by mgonzalezbilli** [federicodonner/pendientes_recargana_IV#23]
El mensaje debería decir "Introduzca su pin"
![IMG-20210227-WA0018](https://user-images.githubusercontent.com/60514253/109395582-de882e80-790b-11eb-9e55-cfd5d33c5677.jpg)

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
Verificado
![IMG_20210301_112656](https://user-images.githubusercontent.com/60514253/109510866-414f0680-7a81-11eb-9c12-1239ded50756.jpg)
