### ISSUE TITLE
Cupones meses anteriores

### ISSUE THREAD

**Issue by mgonzalezbilli** [federicodonner/pendientes_recargana_IV#26]
No deberían computar meses anteriores a Marzo
![Screenshot_2021-03-01-10-40-29-336_com android chrome](https://user-images.githubusercontent.com/60514253/109504871-c97ddd80-7a7a-11eb-833f-33154e8e687e.jpg)

**Comment by joaobastos89** [comment]
Done. Ahora esta en Febrero. En el go live el Febrero va a eliminar automatico y el primero mes queda Marzo, y meses anteriores no aparece

**Comment by mgonzalezbilli** [comment]
Ok rechequearemos mañana

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
Ok.
