### ISSUE TITLE
Some titles look like buttons, they should not have a border

### ISSUE THREAD

**Issue by federicodonner** [federicodonner/pendientes_recargana_IV#27]
"RASPADITAS DISPONIBLES" in RASPADITAS section.
"PREMIOS GANADOS" and "PREMIOS VENCIDOS" in PREMIOS section.

![unnamed](https://user-images.githubusercontent.com/18017111/109506155-16ae7f00-7a7c-11eb-9438-0ed3934350db.jpg)

**Comment by joaobastos89** [comment]
Done

**Comment by federicodonner** [comment]
Verificado.
