### ISSUE TITLE
The prizes carousel's arrows look the same when there are next pictures available then when not

### ISSUE THREAD

**Issue by federicodonner** [federicodonner/pendientes_recargana_IV#28]
The arrows next to the picture of the prizes should change when the user has reached the end of the carousel (also te beginning) and either disappear or change it's style.
Another solution could be to make the carousel loop, I don't like it but it would work.

![unnamed-1](https://user-images.githubusercontent.com/18017111/109506326-45c4f080-7a7c-11eb-9052-90180191de30.jpg)

**Comment by federicodonner** [comment]
For example, because March is the first raffle, there should not be an arrow pointing back.

**Comment by joaobastos89** [comment]
Done. Now it is February, but in the go live February will be eliminated automatically, 1st month will be March and arrow on the left will disappear.

**Comment by federicodonner** [comment]
Verificado.
