### ISSUE TITLE
Change the image behind the raspadita, the first thing that's visible is the bicycle

### ISSUE THREAD

**Issue by federicodonner** [federicodonner/pendientes_recargana_IV#29]
When I scratched, for a second I thought I had won the bicycle. That image is visible for so little time that I don't think it's worth the confusion. Maybe only use the Recarganá logo.

@mgonzalezbilli Confirmá si te parece bien esta sugerencia.

![IMG_3174](https://user-images.githubusercontent.com/18017111/109507469-8bce8400-7a7d-11eb-81ee-54af9d4af556.JPG)

**Comment by mgonzalezbilli** [comment]
Sí, deberíamos ver un paquete de regalo de fondo para evitar reclamos.

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
Solved
![Screenshot_2021-03-01-13-47-21-869_com android chrome](https://user-images.githubusercontent.com/60514253/109529691-bbd55180-7a94-11eb-8f93-83cd366a0697.jpg)
