### ISSUE TITLE
Texto del logo

### ISSUE THREAD

**Issue by mgonzalezbilli** [federicodonner/pendientes_recargana_IV#5]
Cambiar de "Recarganá con Movistar" a "Recarganá de Movistar"
![image](https://user-images.githubusercontent.com/60514253/109299951-a4883100-7814-11eb-8be5-284740c30da3.png)

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
El error sigue sin resolverse.
![image](https://user-images.githubusercontent.com/60514253/109346436-6f99cf80-7850-11eb-97dd-30e5c1497e4e.png)

**Comment by mgonzalezbilli** [comment]
Resuelto
![f4281b41-8acc-42ec-ada6-f2f73e00f6f6](https://user-images.githubusercontent.com/60514253/109351498-25b4e780-7858-11eb-8a6e-9a876ea61a2e.jpg)
