### ISSUE TITLE
Detalle de premios mensuales - Colocar logo de Xiaomi

### ISSUE THREAD

**Issue by mgonzalezbilli** [federicodonner/pendientes_recargana_IV#7]
Poner el logo de Xiaomi en el POP UP de los premios que se sortean mensualmente
![94f60800-50d0-4845-9bac-156b0959047c](https://user-images.githubusercontent.com/60514253/109318432-8cbca700-782c-11eb-9f41-13af75015b1f.jpg)

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
No se actualizó en la raspadita. El caso sigue pendiente.

**Comment by mgonzalezbilli** [comment]
Resuelto
![Uploading caf5e790-369e-4ae9-9561-5762c36b645c.jpg…]()
