### ISSUE TITLE
Al ingresar el link que llega por SMS, no se puede raspar

### ISSUE THREAD

**Issue by mgonzalezbilli** [federicodonner/pendientes_recargana_IV#8]
![39fcf3cd-8b25-4bbc-97ca-bfaee529d7ae](https://user-images.githubusercontent.com/60514253/109318372-7d3d5e00-782c-11eb-8661-e4e2e3e30bd3.jpg)

**Comment by joaobastos89** [comment]
Done

**Comment by mgonzalezbilli** [comment]
Resuelto
